O nosso projeto é sobre os dados que tem no portal do CEAPS (Cota para Exercício da Atividade Parlamentar dos Senadores)

Os topicos:

-   0.0 - Vamos analisar os dados de forma mais criterioas
-   1.0 - 

# Imports

In [557]:
import  pandas  as  pd
import  numpy   as  np

# 0.0 DataSets, analisando os dados

##### Importando todos os dados de 2008 até 2022

In [558]:
df_ceaps_2008 = pd.read_csv('./datasets/despesa_ceaps_2008.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2009 = pd.read_csv('./datasets/despesa_ceaps_2009.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2010 = pd.read_csv('./datasets/despesa_ceaps_2010.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2011 = pd.read_csv('./datasets/despesa_ceaps_2011.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2012 = pd.read_csv('./datasets/despesa_ceaps_2012.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2013 = pd.read_csv('./datasets/despesa_ceaps_2013.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2014 = pd.read_csv('./datasets/despesa_ceaps_2014.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2015 = pd.read_csv('./datasets/despesa_ceaps_2015.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2016 = pd.read_csv('./datasets/despesa_ceaps_2016.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2017 = pd.read_csv('./datasets/despesa_ceaps_2017.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2018 = pd.read_csv('./datasets/despesa_ceaps_2018.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2019 = pd.read_csv('./datasets/despesa_ceaps_2019.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2020 = pd.read_csv('./datasets/despesa_ceaps_2020.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2021 = pd.read_csv('./datasets/despesa_ceaps_2021.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2022 = pd.read_csv('./datasets/despesa_ceaps_2022.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})

##### Concatenando todos os datasets para facilitar a analise, as colunas são do mesmo tamanho e tipo 

In [559]:
df = pd.concat([
    df_ceaps_2008,
    df_ceaps_2009,
    df_ceaps_2010,
    df_ceaps_2011,
    df_ceaps_2012,
    df_ceaps_2013,
    df_ceaps_2014,
    df_ceaps_2015,
    df_ceaps_2016,
    df_ceaps_2017,
    df_ceaps_2018,
    df_ceaps_2019,
    df_ceaps_2020,
    df_ceaps_2021,
    df_ceaps_2022
], axis=0)


##### Quantos dados temos?

R: Temos 317963 registros

In [560]:
len(df)

317963

In [561]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317963 entries, 0 to 16781
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   ANO                317963 non-null  int64 
 1   MES                317963 non-null  int64 
 2   SENADOR            317963 non-null  object
 3   TIPO_DESPESA       317963 non-null  object
 4   CNPJ_CPF           314819 non-null  object
 5   FORNECEDOR         314819 non-null  object
 6   DOCUMENTO          293153 non-null  object
 7   DATA               314819 non-null  object
 8   DETALHAMENTO       180631 non-null  object
 9   VALOR_REEMBOLSADO  317963 non-null  object
 10  COD_DOCUMENTO      317961 non-null  object
dtypes: int64(2), object(9)
memory usage: 29.1+ MB


### Entendendo os campos

##### Novos campos

['ANO_MES'] concatenando os valores ANO + MES

In [562]:
df['ANO_MES'] = pd.to_datetime(df['ANO'].astype(str) + '-' + df['MES'].astype(str), format='%Y-%m')

##### Insert nos campos

In [563]:
# df.loc[df['ANO_MES'] < '2009-04-01', ['DOCUMENTO']] = 'NÃO TINHA CADASTRO'

##### Analisar os campos

In [564]:
df.head()

ANO  MES    SENADOR                                       TIPO_DESPESA  \
0  2008    9  ADA MELLO  Contratação de consultorias, assessorias, pesq...   
1  2008    9  ADA MELLO  Locomoção, hospedagem, alimentação, combustíve...   
2  2008   10  ADA MELLO  Contratação de consultorias, assessorias, pesq...   
3  2008   10  ADA MELLO  Locomoção, hospedagem, alimentação, combustíve...   
4  2008   11  ADA MELLO  Contratação de consultorias, assessorias, pesq...   

  CNPJ_CPF FORNECEDOR DOCUMENTO DATA DETALHAMENTO VALOR_REEMBOLSADO  \
0      NaN        NaN       NaN  NaN          NaN          12351,52   
1      NaN        NaN       NaN  NaN          NaN             386,6   
2      NaN        NaN       NaN  NaN          NaN          12351,52   
3      NaN        NaN       NaN  NaN          NaN           2610,68   
4      NaN        NaN       NaN  NaN          NaN          12351,52   

   COD_DOCUMENTO    ANO_MES  
0  2008090814004 2008-09-01  
1  2008090814003 2008-09-01  
2  2008100814004 2008-10-01  
3  2008100814003 2008-10-01  
4  2008110814004 2008-11-01

<span style="color:red">A principio, não temos dados no campo CNPJ_CPF, FORNECEDORM DOCUMENTO, DATA e DETALHAMENTO</span>

- Verificamos e tem valores, não são todos nulos

In [565]:
df.columns

Index(['ANO', 'MES', 'SENADOR', 'TIPO_DESPESA', 'CNPJ_CPF', 'FORNECEDOR',
       'DOCUMENTO', 'DATA', 'DETALHAMENTO', 'VALOR_REEMBOLSADO',
       'COD_DOCUMENTO', 'ANO_MES'],
      dtype='object')

##### Vamos analisar melhor o campo CNPJ_CPF

- 3144 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03
- Os valores começam a ser preenchidos em 2009-04

<span style="color:green">Não vamos deletar o campo! Acredito que tenham colocado esse campo depois da data 2009-03.</span>
<br>
<span style="color:green">Preenche com "00000000000"</span>

In [566]:
# CNPJ_CPF
df['CNPJ_CPF'].unique()

array([nan, '004.948.028-63', '02.831.112/0002-09', ...,
       '05.044.096/0002-94', '41.365.622/0001-09', '34.307.872/0001-19'],
      dtype=object)

In [567]:
df[df['CNPJ_CPF'].isnull()]['ANO_MES'].min(), df[df['CNPJ_CPF'].isnull()]['ANO_MES'].max()

(Timestamp('2008-02-01 00:00:00'), Timestamp('2009-03-01 00:00:00'))

In [568]:
df[df['CNPJ_CPF'].notna()]['ANO_MES'].min(), df[df['CNPJ_CPF'].notna()]['ANO_MES'].max()

(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

##### Campo FORNECEDOR

- 3144 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03
- Os valores começam a ser preenchidos em 2009-04

<span style="color:green">Não vamos deletar o campo! Acredito que tenham colocado esse campo depois da data 2009-03.</span>
<br>
<span style="color:green">Preenche com "FORNECEDOR NÃO CADASTRADO"</span>

In [569]:
# FORNECEDOR
df['FORNECEDOR'].unique()

array([nan, 'GILBERTO PISELO DO NASCIMENTO',
       'INTERCOM INTERMEDIAÇÕES E COMUNICAÇÃO INTEGRADA LTDA', ...,
       'RCM COMUNICAÇÃO E SERVIÇOS LTDA.',
       'AM & AP COMÉRCIO DE ALIMENTOS LTDA.-ME',
       'J M F COMÉRCIO DE COMBUSTIVEIS LTDA.'], dtype=object)

In [570]:
len(df[df['FORNECEDOR'].isna()])

3144

In [571]:
df[df['FORNECEDOR'].isnull()]['ANO_MES'].min(), df[df['FORNECEDOR'].isnull()]['ANO_MES'].max()

(Timestamp('2008-02-01 00:00:00'), Timestamp('2009-03-01 00:00:00'))

In [572]:
df[df['FORNECEDOR'].notna()]['ANO_MES'].min(), df[df['FORNECEDOR'].notna()]['ANO_MES'].max()

(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

##### Campo DOCUMENTO

- 24810 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03, <span style="color: yellow">mas ainda tem valores nulos depois dessa data</span>
- Valores diferentes de 6 e 7 caracteres estão nulos, <span style="color: yellow"> tem valores nulos com 6 e 7 caracteres</span>
- DOCUMENTO NULO com NUM_LETRAS_COD_DOCUMENTO > 7 o DETALHAMENTO é tudo NULL, <span style="color: yellow"> tem valores nulos com 6 e 7 caracteres</span>


<span style="color:green">Não vamos deletar o campo! Acredito que tenham colocado esse campo depois da data 2009-03.</span>
<br>
<span style="color:green">Preenche com "FORNECEDOR NÃO CADASTRADO"</span>

In [573]:
# DOCUMENTO
df['DOCUMENTO'].unique()

array([nan, '000330', '106471', ..., 'THPKVQ', 'QNN9HX', 'WMQWBX'],
      dtype=object)

In [574]:
len(df[df['DOCUMENTO'].isna()]), len(df[df['DOCUMENTO'].notna()])

(24810, 293153)

In [575]:
df[df['DOCUMENTO'].isnull()]['ANO_MES'].min(), df[df['DOCUMENTO'].isnull()]['ANO_MES'].max()

(Timestamp('2008-02-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

In [576]:
df[df['DOCUMENTO'].notna()]['ANO_MES'].min(), df[df['DOCUMENTO'].notna()]['ANO_MES'].max()

(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

In [577]:
#################################################################
#
#
# Vamos analisar quantidades de numero no COD_DOCUMENTO
# Aparentemente os valores diferentes de 6 e 7 caracteres não tem DOCUMENTOS
#
#################################################################

df['NUM_LETRAS_COD_DOCUMENTO'] = df['COD_DOCUMENTO'].str.len()

In [578]:
print("Valores não NULOS, min e max: {} e {}".format(df[(df['DOCUMENTO'].notna())]['NUM_LETRAS_COD_DOCUMENTO'].min(), df[(df['DOCUMENTO'].notna())]['NUM_LETRAS_COD_DOCUMENTO'].max()))

Valores não NULOS, min e max: 6.0 e 7.0


In [579]:
print("Valores NULOS, min e max: {} e {}".format(df[(df['DOCUMENTO'].isnull())]['NUM_LETRAS_COD_DOCUMENTO'].min(), df[(df['DOCUMENTO'].isnull())]['NUM_LETRAS_COD_DOCUMENTO'].max()))

Valores NULOS, min e max: 6.0 e 13.0


In [580]:
df[(df['DOCUMENTO'].isnull()) & (df['NUM_LETRAS_COD_DOCUMENTO'] < 8)]['DETALHAMENTO'].unique()

array([nan, 'Referente a multa de remarcação.',
       'Senadpr Armando Monteiro Referente a multa de remarcação.', ...,
       'DESPESA DE ALUGUEL DO ESCRITÓRIO DE APOIO DO SENADOR RODRIGO CUNHA - NOVEMBRO 2022',
       'DESPESA DE ALUGUEL DO ESCRITÓRIO DE APOIO DO SENADOR RODRIGO CUNHA EM MACEIÓ DEZEMBRO 2022',
       'Pagamento integral de despesas com IPTU referente ao ano de 2022, do Escritório de Representação da senadora Simone Tebet em Campo Grande/MS.'],
      dtype=object)

In [581]:
df[(df['DOCUMENTO'].isnull()) & (df['NUM_LETRAS_COD_DOCUMENTO'] > 8)]

ANO  MES                         SENADOR  \
0      2008    9                       ADA MELLO   
1      2008    9                       ADA MELLO   
2      2008   10                       ADA MELLO   
3      2008   10                       ADA MELLO   
4      2008   11                       ADA MELLO   
...     ...  ...                             ...   
15952  2009    2  WELLINGTON SALGADO DE OLIVEIRA   
15953  2009    3  WELLINGTON SALGADO DE OLIVEIRA   
15954  2009    3  WELLINGTON SALGADO DE OLIVEIRA   
15955  2009    3  WELLINGTON SALGADO DE OLIVEIRA   
15956  2009    3  WELLINGTON SALGADO DE OLIVEIRA   

                                            TIPO_DESPESA CNPJ_CPF FORNECEDOR  \
0      Contratação de consultorias, assessorias, pesq...      NaN        NaN   
1      Locomoção, hospedagem, alimentação, combustíve...      NaN        NaN   
2      Contratação de consultorias, assessorias, pesq...      NaN        NaN   
3      Locomoção, hospedagem, alimentação, combustíve...      NaN        NaN   
4      Contratação de consultorias, assessorias, pesq...      NaN        NaN   
...                                                  ...      ...        ...   
15952  Locomoção, hospedagem, alimentação, combustíve...      NaN        NaN   
15953  Aluguel de imóveis para escritório político, c...      NaN        NaN   
15954  Aquisição de material de consumo para uso no e...      NaN        NaN   
15955  Contratação de consultorias, assessorias, pesq...      NaN        NaN   
15956  Locomoção, hospedagem, alimentação, combustíve...      NaN        NaN   

      DOCUMENTO DATA DETALHAMENTO VALOR_REEMBOLSADO  COD_DOCUMENTO    ANO_MES  \
0           NaN  NaN          NaN          12351,52  2008090814004 2008-09-01   
1           NaN  NaN          NaN             386,6  2008090814003 2008-09-01   
2           NaN  NaN          NaN          12351,52  2008100814004 2008-10-01   
3           NaN  NaN          NaN           2610,68  2008100814003 2008-10-01   
4           NaN  NaN          NaN          12351,52  2008110814004 2008-11-01   
...         ...  ...          ...               ...            ...        ...   
15952       NaN  NaN          NaN           3058,13  2009020587703 2009-02-01   
15953       NaN  NaN          NaN           2988,72  2009030587701 2009-03-01   
15954       NaN  NaN          NaN            599,56  2009030587702 2009-03-01   
15955       NaN  NaN          NaN              3480  2009030587704 2009-03-01   
15956       NaN  NaN          NaN           4261,92  2009030587703 2009-03-01   

       NUM_LETRAS_COD_DOCUMENTO  
0                          13.0  
1                          13.0  
2                          13.0  
3                          13.0  
4                          13.0  
...                         ...  
15952                      13.0  
15953                      13.0  
15954                      13.0  
15955                      13.0  
15956                      13.0  

[3144 rows x 13 columns]

In [582]:
df['DETALHAMENTO'].unique()

array([nan,
       'BILHETE UTILIZADO PELO SENADOR ACIR GURGACZ. TRECHO: BRASÍLIA/ CUIABÁ. TAM-VOO-JJ-3648. DIA22/JUN/2011.',
       'BILHETE UTILIZADO PELO SENADOR ACIR GURGACZ. TRECHO: PORTO VELHO/BRASÍLIA. TAM-VOO-JJ-3687. DIA-27/JUN/2011.',
       ...,
       'Companhia Aérea: TAM, Localizador: THPKVQ. Passageiros: JOSÉ DA CRUZ MARINHO (Matrícula 341141, PARLAMENTAR), Voo: 3608 - BSB/BELÉM - 22/12/2022;',
       'Companhia Aérea: AZUL, Localizador: QNN9HX. Passageiros: JOSÉ DA CRUZ MARINHO (Matrícula 341141, PARLAMENTAR), Voo: 4112 - BEL/MAB - 23/12/2022;',
       'Companhia Aérea: TAM, Localizador: WMQWBX. Passageiros: YURI PEREIRA CARNEIRO AGE (Matrícula 300461, COMISSIONADO), Voo: 3608 - BSB/BELÉM - 08/01/2023; YURI PEREIRA CARNEIRO AGE (Matrícula 300461, COMISSIONADO), Voo: 3609 - BELÉM/BSB - 20/01/2023;'],
      dtype=object)

In [583]:
# len(df[df['DOCUMENTO'].isnull()]['COD_DOCUMENTO'].unique())
len(df[df['DOCUMENTO'].notna()]['COD_DOCUMENTO'].unique())

293152

Campo DATA

In [584]:
# DATA
df['DATA'].unique()

array([nan, '11/12/2009', '09/12/2009', ..., '09/03/2023', '23/01/2023',
       '01/02/2023'], dtype=object)

Campo DETALHAMENTO

In [585]:
# DETALHAMENTO
df_ceaps_2008['DETALHAMENTO'].unique()

array([nan])

Identificando o encoding para conseguir ler o arquivo de forma certa

In [586]:
# # Tente ler o arquivo CSV usando diferentes codificações até encontrar a correta
# possible_encodings = ['utf-8', 'latin1', 'ISO-8859-1', 'cp1252']

# for encoding in possible_encodings:
#     try:
#         df_ceaps_2022 = pd.read_csv('./datasets/despesa_ceaps_2008.csv', encoding=encoding, sep=';')
#         print(f"Arquivo lido com sucesso usando a codificação: {encoding}")
#         break
#     except UnicodeDecodeError:
#         print(f"Erro ao ler o arquivo com a codificação: {encoding}")

# # Agora 'df' contém os dados do seu arquivo CSV em um DataFrame do pandas
