O nosso projeto é sobre os dados que tem no portal do CEAPS (Cota para Exercício da Atividade Parlamentar dos Senadores)

Os topicos:

-   0.0 - Vamos analisar os dados de forma mais criterioas
-   1.0 - 

# Imports

In [1]:
import  pandas  as  pd
import  numpy   as  np

import  re

# 0.0 DataSets, analisando os dados

##### Importando todos os dados de 2008 até 2022

In [2]:
df_ceaps_2008 = pd.read_csv('./datasets/despesa_ceaps_2008.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2009 = pd.read_csv('./datasets/despesa_ceaps_2009.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2010 = pd.read_csv('./datasets/despesa_ceaps_2010.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2011 = pd.read_csv('./datasets/despesa_ceaps_2011.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2012 = pd.read_csv('./datasets/despesa_ceaps_2012.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2013 = pd.read_csv('./datasets/despesa_ceaps_2013.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2014 = pd.read_csv('./datasets/despesa_ceaps_2014.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2015 = pd.read_csv('./datasets/despesa_ceaps_2015.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2016 = pd.read_csv('./datasets/despesa_ceaps_2016.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2017 = pd.read_csv('./datasets/despesa_ceaps_2017.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2018 = pd.read_csv('./datasets/despesa_ceaps_2018.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2019 = pd.read_csv('./datasets/despesa_ceaps_2019.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2020 = pd.read_csv('./datasets/despesa_ceaps_2020.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2021 = pd.read_csv('./datasets/despesa_ceaps_2021.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})
df_ceaps_2022 = pd.read_csv('./datasets/despesa_ceaps_2022.csv', encoding='ISO-8859-1', sep=';', skiprows=1, dtype={'COD_DOCUMENTO': str})

##### Concatenando todos os datasets para facilitar a analise, as colunas são do mesmo tamanho e tipo 

In [3]:
df = pd.concat([
    df_ceaps_2008,
    df_ceaps_2009,
    df_ceaps_2010,
    df_ceaps_2011,
    df_ceaps_2012,
    df_ceaps_2013,
    df_ceaps_2014,
    df_ceaps_2015,
    df_ceaps_2016,
    df_ceaps_2017,
    df_ceaps_2018,
    df_ceaps_2019,
    df_ceaps_2020,
    df_ceaps_2021,
    df_ceaps_2022
], axis=0)


##### Quantos dados temos?

R: Temos 317963 registros

In [4]:
len(df)

317963

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 317963 entries, 0 to 16781
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype 
---  ------             --------------   ----- 
 0   ANO                317963 non-null  int64 
 1   MES                317963 non-null  int64 
 2   SENADOR            317963 non-null  object
 3   TIPO_DESPESA       317963 non-null  object
 4   CNPJ_CPF           314819 non-null  object
 5   FORNECEDOR         314819 non-null  object
 6   DOCUMENTO          293153 non-null  object
 7   DATA               314819 non-null  object
 8   DETALHAMENTO       180631 non-null  object
 9   VALOR_REEMBOLSADO  317963 non-null  object
 10  COD_DOCUMENTO      317961 non-null  object
dtypes: int64(2), object(9)
memory usage: 29.1+ MB


### Entendendo os campos

##### Novos campos

['ANO_MES'] concatenando os valores ANO + MES

In [6]:
df['ANO_MES'] = pd.to_datetime(df['ANO'].astype(str) + '-' + df['MES'].astype(str), format='%Y-%m')

In [7]:
#################################################################
#
#
# Vamos analisar quantidades de numero no COD_DOCUMENTO
# Aparentemente os valores diferentes de 6 e 7 caracteres não tem DOCUMENTOS
#
#################################################################

df['NUM_LETRAS_COD_DOCUMENTO'] = df['COD_DOCUMENTO'].str.len()

##### Insert nos campos

In [8]:
# df.loc[df['ANO_MES'] < '2009-04-01', ['DOCUMENTO']] = 'NÃO TINHA CADASTRO'

##### Analisar os campos

In [9]:
df.head()

ANO  MES    SENADOR                                       TIPO_DESPESA  \
0  2008    9  ADA MELLO  Contratação de consultorias, assessorias, pesq...   
1  2008    9  ADA MELLO  Locomoção, hospedagem, alimentação, combustíve...   
2  2008   10  ADA MELLO  Contratação de consultorias, assessorias, pesq...   
3  2008   10  ADA MELLO  Locomoção, hospedagem, alimentação, combustíve...   
4  2008   11  ADA MELLO  Contratação de consultorias, assessorias, pesq...   

  CNPJ_CPF FORNECEDOR DOCUMENTO DATA DETALHAMENTO VALOR_REEMBOLSADO  \
0      NaN        NaN       NaN  NaN          NaN          12351,52   
1      NaN        NaN       NaN  NaN          NaN             386,6   
2      NaN        NaN       NaN  NaN          NaN          12351,52   
3      NaN        NaN       NaN  NaN          NaN           2610,68   
4      NaN        NaN       NaN  NaN          NaN          12351,52   

   COD_DOCUMENTO    ANO_MES  NUM_LETRAS_COD_DOCUMENTO  
0  2008090814004 2008-09-01                      13.0  
1  2008090814003 2008-09-01                      13.0  
2  2008100814004 2008-10-01                      13.0  
3  2008100814003 2008-10-01                      13.0  
4  2008110814004 2008-11-01                      13.0

<span style="color:red">A principio, não temos dados no campo CNPJ_CPF, FORNECEDORM DOCUMENTO, DATA e DETALHAMENTO</span>

- Verificamos e tem valores, não são todos nulos

In [10]:
df.columns

Index(['ANO', 'MES', 'SENADOR', 'TIPO_DESPESA', 'CNPJ_CPF', 'FORNECEDOR',
       'DOCUMENTO', 'DATA', 'DETALHAMENTO', 'VALOR_REEMBOLSADO',
       'COD_DOCUMENTO', 'ANO_MES', 'NUM_LETRAS_COD_DOCUMENTO'],
      dtype='object')

##### Vamos analisar melhor o campo CNPJ_CPF

- 3144 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03
- Os valores começam a ser preenchidos em 2009-04

<span style="color:green">Não vamos deletar o campo! Acredito que tenham colocado esse campo depois da data 2009-03.</span>
<br>
<span style="color:green">Preenche com "00000000000"</span>

In [11]:
# CNPJ_CPF
df['CNPJ_CPF'].unique()

array([nan, '004.948.028-63', '02.831.112/0002-09', ...,
       '05.044.096/0002-94', '41.365.622/0001-09', '34.307.872/0001-19'],
      dtype=object)

In [12]:
df[df['CNPJ_CPF'].isnull()]['ANO_MES'].min(), df[df['CNPJ_CPF'].isnull()]['ANO_MES'].max()

(Timestamp('2008-02-01 00:00:00'), Timestamp('2009-03-01 00:00:00'))

In [13]:
df[df['CNPJ_CPF'].notna()]['ANO_MES'].min(), df[df['CNPJ_CPF'].notna()]['ANO_MES'].max()

(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

##### Campo FORNECEDOR

- 3144 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03
- Os valores começam a ser preenchidos em 2009-04

<span style="color:green">Não vamos deletar o campo! Acredito que tenham colocado esse campo depois da data 2009-03.</span>
<br>
<span style="color:green">Preenche com "FORNECEDOR NÃO CADASTRADO"</span>

In [14]:
# FORNECEDOR
df['FORNECEDOR'].unique()

array([nan, 'GILBERTO PISELO DO NASCIMENTO',
       'INTERCOM INTERMEDIAÇÕES E COMUNICAÇÃO INTEGRADA LTDA', ...,
       'RCM COMUNICAÇÃO E SERVIÇOS LTDA.',
       'AM & AP COMÉRCIO DE ALIMENTOS LTDA.-ME',
       'J M F COMÉRCIO DE COMBUSTIVEIS LTDA.'], dtype=object)

In [15]:
len(df[df['FORNECEDOR'].isna()])

3144

In [16]:
df[df['FORNECEDOR'].isnull()]['ANO_MES'].min(), df[df['FORNECEDOR'].isnull()]['ANO_MES'].max()

(Timestamp('2008-02-01 00:00:00'), Timestamp('2009-03-01 00:00:00'))

In [17]:
df[df['FORNECEDOR'].notna()]['ANO_MES'].min(), df[df['FORNECEDOR'].notna()]['ANO_MES'].max()

(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

##### Campo DOCUMENTO

- 24810 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03, <span style="color: yellow">mas ainda tem valores nulos depois dessa data</span>
- Valores diferentes de 6 e 7 caracteres estão nulos, <span style="color: yellow"> tem valores nulos com 6 e 7 caracteres</span>
- DOCUMENTO NULO com NUM_LETRAS_COD_DOCUMENTO > 7 o DETALHAMENTO é tudo NULL, <span style="color: yellow"> tem valores nulos com 6 e 7 caracteres</span>



<span style="color:red">Não achamos nada especifico, vamos analisar melhor nos graficos.</span>

In [18]:
# DOCUMENTO
df['DOCUMENTO'].unique()

array([nan, '000330', '106471', ..., 'THPKVQ', 'QNN9HX', 'WMQWBX'],
      dtype=object)

In [19]:
len(df[df['DOCUMENTO'].isna()]), len(df[df['DOCUMENTO'].notna()])

(24810, 293153)

Vendo se tem NUM_LETRAS_COD_DOCUMENTO > 8 na epoca que não tinha dados

In [20]:
len(df.loc[( (df['ANO_MES'] < '2009-04-01') & (df['NUM_LETRAS_COD_DOCUMENTO'] > 8) )]), len( df.loc[df['ANO_MES'] < '2009-04-01' ] )

(3144, 3144)

In [21]:
print("Nulos")
df[df['DOCUMENTO'].isnull()]['ANO_MES'].min(), df[df['DOCUMENTO'].isnull()]['ANO_MES'].max()

Nulos


(Timestamp('2008-02-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

In [22]:
print("Não nulos")
df[df['DOCUMENTO'].notna()]['ANO_MES'].min(), df[df['DOCUMENTO'].notna()]['ANO_MES'].max()

Não nulos


(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

In [23]:
print("Valores não NULOS, min e max: {} e {}".format(df[(df['DOCUMENTO'].notna())]['NUM_LETRAS_COD_DOCUMENTO'].min(), df[(df['DOCUMENTO'].notna())]['NUM_LETRAS_COD_DOCUMENTO'].max()))

Valores não NULOS, min e max: 6.0 e 7.0


In [24]:
print("Valores NULOS, min e max: {} e {}".format(df[(df['DOCUMENTO'].isnull())]['NUM_LETRAS_COD_DOCUMENTO'].min(), df[(df['DOCUMENTO'].isnull())]['NUM_LETRAS_COD_DOCUMENTO'].max()))

Valores NULOS, min e max: 6.0 e 13.0


In [25]:
df[(df['DOCUMENTO'].isnull()) & (df['NUM_LETRAS_COD_DOCUMENTO'] < 8)]['DETALHAMENTO'].unique()

array([nan, 'Referente a multa de remarcação.',
       'Senadpr Armando Monteiro Referente a multa de remarcação.', ...,
       'DESPESA DE ALUGUEL DO ESCRITÓRIO DE APOIO DO SENADOR RODRIGO CUNHA - NOVEMBRO 2022',
       'DESPESA DE ALUGUEL DO ESCRITÓRIO DE APOIO DO SENADOR RODRIGO CUNHA EM MACEIÓ DEZEMBRO 2022',
       'Pagamento integral de despesas com IPTU referente ao ano de 2022, do Escritório de Representação da senadora Simone Tebet em Campo Grande/MS.'],
      dtype=object)

In [26]:
df['DETALHAMENTO'].unique()

array([nan,
       'BILHETE UTILIZADO PELO SENADOR ACIR GURGACZ. TRECHO: BRASÍLIA/ CUIABÁ. TAM-VOO-JJ-3648. DIA22/JUN/2011.',
       'BILHETE UTILIZADO PELO SENADOR ACIR GURGACZ. TRECHO: PORTO VELHO/BRASÍLIA. TAM-VOO-JJ-3687. DIA-27/JUN/2011.',
       ...,
       'Companhia Aérea: TAM, Localizador: THPKVQ. Passageiros: JOSÉ DA CRUZ MARINHO (Matrícula 341141, PARLAMENTAR), Voo: 3608 - BSB/BELÉM - 22/12/2022;',
       'Companhia Aérea: AZUL, Localizador: QNN9HX. Passageiros: JOSÉ DA CRUZ MARINHO (Matrícula 341141, PARLAMENTAR), Voo: 4112 - BEL/MAB - 23/12/2022;',
       'Companhia Aérea: TAM, Localizador: WMQWBX. Passageiros: YURI PEREIRA CARNEIRO AGE (Matrícula 300461, COMISSIONADO), Voo: 3608 - BSB/BELÉM - 08/01/2023; YURI PEREIRA CARNEIRO AGE (Matrícula 300461, COMISSIONADO), Voo: 3609 - BELÉM/BSB - 20/01/2023;'],
      dtype=object)

In [27]:
# len(df[df['DOCUMENTO'].isnull()]['COD_DOCUMENTO'].unique())
len(df[df['DOCUMENTO'].notna()]['COD_DOCUMENTO'].unique())

293152

##### Campo DATA

- 3144 dos dados estão com os valores nulos
- Valores nulos de 2008-02 até 2009-03
- Os valores começam a ser preenchidos em 2009-04
-------------------------
- Valores diferentes de 6 e 7 caracteres estão nulos, <span style="color: yellow"> tem valores nulos com 6 e 7 caracteres</span>
- DOCUMENTO NULO com NUM_LETRAS_COD_DOCUMENTO > 7 o DETALHAMENTO é tudo NULL, <span style="color: yellow"> tem valores nulos com 6 e 7 caracteres</span>


<span style="color:green">Não vamos deletar o campo! Acredito que tenham colocado esse campo depois da data 2009-03.</span>
<br>
<span style="color:green">Preenche com "FORNECEDOR NÃO CADASTRADO"</span>

In [28]:
len(df[df['DATA'].isnull()])

3144

In [29]:
print('NULOS')
df[df['DATA'].isnull()]['ANO_MES'].min(), df[df['DATA'].isnull()]['ANO_MES'].max()

NULOS


(Timestamp('2008-02-01 00:00:00'), Timestamp('2009-03-01 00:00:00'))

In [30]:
print('NÃO NULOS')
df[df['DATA'].notna()]['ANO_MES'].min(), df[df['DATA'].notna()]['ANO_MES'].max()

NÃO NULOS


(Timestamp('2009-04-01 00:00:00'), Timestamp('2022-12-01 00:00:00'))

Verificando a diferença dos campos ANO_MES e DATA

Removendo os valores NULOS

In [31]:
df_aux = df[df['DATA'].notna()] 

Verificando os formatados diferentes de data

- Identificamos que foi um erro no CSV, então vamos eliminar esses casos que apareceram.
- Tem dados que tem espaços, vamos tirar

In [32]:
regex_data = re.compile(r"^(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/\d{4}$")
df_aux[~df_aux['DATA'].str.contains(regex_data)]

C:\Users\ferna\AppData\Local\Temp\ipykernel_5028\1099961831.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_aux[~df_aux['DATA'].str.contains(regex_data)]


ANO  MES         SENADOR  \
5922  2015    8  EDUARDO AMORIM   
5929  2015    8  EDUARDO AMORIM   

                                           TIPO_DESPESA            CNPJ_CPF  \
5922  Passagens aéreas, aquáticas e terrestres nacio...  13.353.495/0001-84   
5929  Passagens aéreas, aquáticas e terrestres nacio...  13.353.495/0001-84   

                           FORNECEDOR                  DOCUMENTO  \
5922  PROPAGTUR - Propag Turismo Ltda    SEM FATURA";02/08/2015"   
5929  PROPAGTUR - Propag Turismo Ltda  ¨¨SEM FATURA";17/08/2015"   

                                                   DATA DETALHAMENTO  \
5922  Companhia Aérea: TAM, Localizador: YXGDSJ. Pas...       469,53   
5929  Companhia Aérea: AVIANCA, Localizador: ZNEU9F....       460,45   

     VALOR_REEMBOLSADO COD_DOCUMENTO    ANO_MES  NUM_LETRAS_COD_DOCUMENTO  
5922           2014675           NaN 2015-08-01                       NaN  
5929           2016557           NaN 2015-08-01                       NaN

In [33]:
# Vamos fazer um REGEX para capturar as DATAS com formatos certos
regex_data      =   re.compile(r"^(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/\d{4}$")
df_aux          =   df_aux[df_aux['DATA'].str.contains(regex_data)]

C:\Users\ferna\AppData\Local\Temp\ipykernel_5028\1755870735.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_aux          =   df_aux[df_aux['DATA'].str.contains(regex_data)]


In [34]:
df_aux['DATA_2']  =   pd.to_datetime(
                        df_aux[df_aux['DATA'].str.contains(regex_data)]['DATA']
                        # format='mixed'
                        , format='%d/%m/%Y'
                        , errors='coerce'
                    )


C:\Users\ferna\AppData\Local\Temp\ipykernel_5028\2451307728.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_aux[df_aux['DATA'].str.contains(regex_data)]['DATA']


In [35]:
dt_diferente    =  df_aux[df_aux['DATA_2'].dt.strftime("%m/%Y") != df_aux['ANO_MES'].dt.strftime("%m/%Y")]
dt_igual        =  df_aux[df_aux['DATA_2'].dt.strftime("%m/%Y") == df_aux['ANO_MES'].dt.strftime("%m/%Y")]

In [36]:
dt_diferente.head()

ANO  MES          SENADOR  \
10  2009    5  ADELMIR SANTANA   
23  2009    8  ADELMIR SANTANA   
24  2009    8  ADELMIR SANTANA   
25  2009    9  ADELMIR SANTANA   
27  2009   10  ADELMIR SANTANA   

                                         TIPO_DESPESA            CNPJ_CPF  \
10  Contratação de consultorias, assessorias, pesq...  02.142.987/0001-04   
23  Contratação de consultorias, assessorias, pesq...  02.142.987/0001-04   
24  Contratação de consultorias, assessorias, pesq...  01.666.674/0001-92   
25  Contratação de consultorias, assessorias, pesq...  02.142.987/0001-04   
27                Divulgação da atividade parlamentar  09.320.613/0001-80   

                                           FORNECEDOR DOCUMENTO        DATA  \
10  C A Guimarães Baião Consultores Associados S/S...      0202  05/06/2009   
23  CA Guimarães Baião Consultores Associados S/S ...       223  30/03/2010   
24                           CAC Consultoria Política       337  02/09/2009   
25  CA Guimarães Baião Consultores Associados S/S ...       224  30/03/2010   
27                    KRV Vídeos e Marketing Ltda EPP       255  30/03/2010   

   DETALHAMENTO VALOR_REEMBOLSADO COD_DOCUMENTO    ANO_MES  \
10          NaN             12475        167178 2009-05-01   
23          NaN             10500        251383 2009-08-01   
24          NaN              3000        209474 2009-08-01   
25          NaN             12000        251384 2009-09-01   
27          NaN             14850        251385 2009-10-01   

    NUM_LETRAS_COD_DOCUMENTO     DATA_2  
10                       6.0 2009-06-05  
23                       6.0 2010-03-30  
24                       6.0 2009-09-02  
25                       6.0 2010-03-30  
27                       6.0 2010-03-30

In [37]:
dt_igual.head()

ANO  MES          SENADOR  \
0  2009   12     ACIR GURGACZ   
1  2009   12     ACIR GURGACZ   
7  2009    4  ADELMIR SANTANA   
8  2009    4  ADELMIR SANTANA   
9  2009    4  ADELMIR SANTANA   

                                        TIPO_DESPESA            CNPJ_CPF  \
0  Aluguel de imóveis para escritório político, c...      004.948.028-63   
1                Divulgação da atividade parlamentar  02.831.112/0002-09   
7  Locomoção, hospedagem, alimentação, combustíve...  00.306.597/0016-83   
8  Locomoção, hospedagem, alimentação, combustíve...  00.358.192/0001-02   
9  Locomoção, hospedagem, alimentação, combustíve...  06.098.111/0001-69   

                                          FORNECEDOR DOCUMENTO        DATA  \
0                      GILBERTO PISELO DO NASCIMENTO       NaN  11/12/2009   
1  INTERCOM INTERMEDIAÇÕES E COMUNICAÇÃO INTEGRAD...    000330  09/12/2009   
7             Cascol combustíveis para veículos Ltda    106471  12/04/2009   
8                             Ribeiro e Pereira Ltda     77472  04/04/2009   
9             Tudo de Bom Comércio de alimentos Ltda     10169  14/04/2009   

  DETALHAMENTO VALOR_REEMBOLSADO COD_DOCUMENTO    ANO_MES  \
0          NaN              5000        222467 2009-12-01   
1          NaN             12620        222466 2009-12-01   
7          NaN            179,01        165740 2009-04-01   
8          NaN                30        165739 2009-04-01   
9          NaN             215,8        165741 2009-04-01   

   NUM_LETRAS_COD_DOCUMENTO     DATA_2  
0                       6.0 2009-12-11  
1                       6.0 2009-12-09  
7                       6.0 2009-04-12  
8                       6.0 2009-04-04  
9                       6.0 2009-04-14

##### Campo DETALHAMENTO

In [38]:
# DETALHAMENTO
df_ceaps_2008['DETALHAMENTO'].unique()

array([nan])

Identificando o encoding para conseguir ler o arquivo de forma certa

In [39]:
# # Tente ler o arquivo CSV usando diferentes codificações até encontrar a correta
# possible_encodings = ['utf-8', 'latin1', 'ISO-8859-1', 'cp1252']

# for encoding in possible_encodings:
#     try:
#         df_ceaps_2022 = pd.read_csv('./datasets/despesa_ceaps_2008.csv', encoding=encoding, sep=';')
#         print(f"Arquivo lido com sucesso usando a codificação: {encoding}")
#         break
#     except UnicodeDecodeError:
#         print(f"Erro ao ler o arquivo com a codificação: {encoding}")

# # Agora 'df' contém os dados do seu arquivo CSV em um DataFrame do pandas
